INSERT INTO symbols (symbol, name, icon_url) VALUES
                                                 ('BTC/USD', 'Bitcoin', 'https://cryptologos.cc/logos/bitcoin-btc-logo.png'),
                                                 ('ETH/USD', 'Ethereum', 'https://cryptologos.cc/logos/ethereum-eth-logo.png'),
                                                 ('USDT/USD', 'Tether', 'https://cryptologos.cc/logos/tether-usdt-logo.png'),
                                                 ('BNB/USD', 'BNB', 'https://cryptologos.cc/logos/bnb-bnb-logo.png'),
                                                 ('SOL/USD', 'Solana', 'https://cryptologos.cc/logos/solana-sol-logo.png'),
                                                 ('XRP/USD', 'XRP', 'https://cryptologos.cc/logos/xrp-xrp-logo.png'),
                                                 ('USDC/USD', 'USD Coin', 'https://cryptologos.cc/logos/usd-coin-usdc-logo.png'),
                                                 ('ADA/USD', 'Cardano', 'https://cryptologos.cc/logos/cardano-ada-logo.png'),
                                                 ('DOGE/USD', 'Dogecoin', 'https://cryptologos.cc/logos/dogecoin-doge-logo.png'),
                                                 ('AVAX/USD', 'Avalanche', 'https://cryptologos.cc/logos/avalanche-avax-logo.png'),
                                                 ('SHIB/USD', 'Shiba Inu', 'https://cryptologos.cc/logos/shiba-inu-shib-logo.png'),
                                                 ('DOT/USD', 'Polkadot', 'https://cryptologos.cc/logos/polkadot-new-dot-logo.png'),
                                                 ('TRX/USD', 'Tron', 'https://cryptologos.cc/logos/tron-trx-logo.png'),
                                                 ('LINK/USD', 'Chainlink', 'https://cryptologos.cc/logos/chainlink-link-logo.png'),
                                                 ('MATIC/USD', 'Polygon', 'https://cryptologos.cc/logos/polygon-matic-logo.png'),
                                                 ('WBTC/USD', 'Wrapped Bitcoin', 'https://cryptologos.cc/logos/wrapped-bitcoin-wbtc-logo.png'),
                                                 ('LTC/USD', 'Litecoin', 'https://cryptologos.cc/logos/litecoin-ltc-logo.png'),
                                                 ('BCH/USD', 'Bitcoin Cash', 'https://cryptologos.cc/logos/bitcoin-cash-bch-logo.png'),
                                                 ('UNI/USD', 'Uniswap', 'https://cryptologos.cc/logos/uniswap-uni-logo.png'),
                                                 ('ICP/USD', 'Internet Computer', 'https://cryptologos.cc/logos/internet-computer-icp-logo.png'),
                                                 ('ETC/USD', 'ETC', 'ETC'),
                                                 ('FIL/USD','FIL','FIL'),
                                                 ('ATOM/USD', 'ATOM', 'ATOM'),
                                                 ('APE/USD','APE','APE'),
                                                 ('XLM/USD','XLM','XLM'),
                                                 ('ETC', 'ETC', 'ETC');

