package com.example.tradingappdemo.response;

public enum ResponseResult {
    BAD_AUTHENTICATION,
    EMAIL_INVALID,
    EMAIL_TAKEN,
    INSUFFICIENT_FUNDS,
    INVALID_SYMBOL,
    NEGATIVE_AMOUNT,
    PASSWORD_INVALID_CHARACTERS,
    PASSWORD_TOO_LONG,
    PASSWORD_TOO_SHORT,
    PRICE_UNAVAILABLE,
    SUCCESS,
    SUCCESSFUL_BUY,
    SUCCESSFUL_REGISTRATION,
    SUCCESSFUL_RESET,
    SUCCESSFUL_SALE,
    USERNAME_INVALID_CHARACTERS,
    USERNAME_TAKEN,
    USERNAME_TOO_LONG,
    USERNAME_TOO_SHORT,
    EMAIL_TOO_LONG,
}
